/*
 *   Copyright (c) 2010, Michael Lehn
 *
 *   All rights reserved.
 *
 *   Redistribution and use in source and binary forms, with or without
 *   modification, are permitted provided that the following conditions
 *   are met:
 *
 *   1) Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *   2) Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in
 *      the documentation and/or other materials provided with the
 *      distribution.
 *   3) Neither the name of the FLENS development group nor the names of
 *      its contributors may be used to endorse or promote products derived
 *      from this software without specific prior written permission.
 *
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *   OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *   DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *   THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *   OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifdef FLENS_BLASLOG_SETTAG
#undef FLENS_BLASLOG_SETTAG
#endif

#ifdef FLENS_BLASLOG_UNSETTAG
#undef FLENS_BLASLOG_UNSETTAG
#endif

#ifdef FLENS_BLASLOG_END
#undef FLENS_BLASLOG_END
#endif

#ifdef FLENS_BLASLOG_BEGIN_ASSIGNMENT
#undef FLENS_BLASLOG_BEGIN_ASSIGNMENT
#endif

#ifdef FLENS_BLASLOG_BEGIN_PLUSASSIGNMENT
#undef FLENS_BLASLOG_BEGIN_PLUSASSIGNMENT
#endif

#ifdef FLENS_BLASLOG_BEGIN_MINUSASSIGNMENT
#undef FLENS_BLASLOG_BEGIN_MINUSASSIGNMENT
#endif

#ifdef FLENS_BLASLOG_IDENTICAL
#undef FLENS_BLASLOG_IDENTICAL
#endif

#ifdef FLENS_BLASLOG_TMP_ADD
#undef FLENS_BLASLOG_TMP_ADD
#endif
#ifdef FLENS_BLASLOG_TMP_TRON
#undef FLENS_BLASLOG_TMP_TRON
#endif
#ifdef FLENS_BLASLOG_TMP_TROFF
#undef FLENS_BLASLOG_TMP_TROFF
#endif
#ifdef FLENS_BLASLOG_TMP_REMOVE
#undef FLENS_BLASLOG_TMP_REMOVE
#endif

#ifdef FLENS_BLASLOG_ERROR_COPY
#undef FLENS_BLASLOG_ERROR_COPY
#endif
#ifdef FLENS_BLASLOG_ERROR_MCOPY
#undef FLENS_BLASLOG_ERROR_MCOPY
#endif
#ifdef FLENS_BLASLOG_ERROR_AXPY
#undef FLENS_BLASLOG_ERROR_AXPY
#endif
#ifdef FLENS_BLASLOG_ERROR_MAXPY
#undef FLENS_BLASLOG_ERROR_MAXPY
#endif

#ifdef FLENS_BLASLOG_RESIZE_VECTOR
#undef FLENS_BLASLOG_RESIZE_VECTOR
#endif
#ifdef FLENS_BLASLOG_RESIZE_MATRIX
#undef FLENS_BLASLOG_RESIZE_MATRIX
#endif
#ifdef FLENS_BLASLOG_RESIZE_GBMATRIX
#undef FLENS_BLASLOG_RESIZE_GBMATRIX
#endif
#ifdef FLENS_BLASLOG_RESIZE_HBMATRIX
#undef FLENS_BLASLOG_RESIZE_HBMATRIX
#endif
#ifdef FLENS_BLASLOG_RESIZE_SBMATRIX
#undef FLENS_BLASLOG_RESIZE_SBMATRIX
#endif
#ifdef FLENS_BLASLOG_RESIZE_TBMATRIX
#undef FLENS_BLASLOG_RESIZE_TBMATRIX
#endif

#ifdef FLENS_BLASLOG_BEGIN_COPY
#undef FLENS_BLASLOG_BEGIN_COPY
#endif
#ifdef FLENS_BLASLOG_BEGIN_RESIDUAL
#undef FLENS_BLASLOG_BEGIN_RESIDUAL
#endif
#ifdef FLENS_BLASLOG_BEGIN_MCOPY
#undef FLENS_BLASLOG_BEGIN_MCOPY
#endif
#ifdef FLENS_BLASLOG_BEGIN_MCOTR
#undef FLENS_BLASLOG_BEGIN_MCOTR
#endif
#ifdef FLENS_BLASLOG_BEGIN_AXPY
#undef FLENS_BLASLOG_BEGIN_AXPY
#endif
#ifdef FLENS_BLASLOG_BEGIN_MAXPY
#undef FLENS_BLASLOG_BEGIN_MAXPY
#endif
#ifdef FLENS_BLASLOG_BEGIN_RAXPY
#undef FLENS_BLASLOG_BEGIN_RAXPY
#endif
#ifdef FLENS_BLASLOG_BEGIN_MRAXPY
#undef FLENS_BLASLOG_BEGIN_MRAXPY
#endif
#ifdef FLENS_BLASLOG_BEGIN_SCAL
#undef FLENS_BLASLOG_BEGIN_SCAL
#endif
#ifdef FLENS_BLASLOG_BEGIN_RSCAL
#undef FLENS_BLASLOG_BEGIN_RSCAL
#endif
#ifdef FLENS_BLASLOG_BEGIN_DOT
#undef FLENS_BLASLOG_BEGIN_DOT
#endif
#ifdef FLENS_BLASLOG_BEGIN_DOTU
#undef FLENS_BLASLOG_BEGIN_DOTU
#endif

#ifdef FLENS_BLASLOG_BEGIN_HBMV
#undef FLENS_BLASLOG_BEGIN_HBMV
#endif
#ifdef FLENS_BLASLOG_BEGIN_HEMV
#undef FLENS_BLASLOG_BEGIN_HEMV
#endif
#ifdef FLENS_BLASLOG_BEGIN_HPMV
#undef FLENS_BLASLOG_BEGIN_HPMV
#endif

#ifdef FLENS_BLASLOG_BEGIN_GEMV
#undef FLENS_BLASLOG_BEGIN_GEMV
#endif
#ifdef FLENS_BLASLOG_BEGIN_GBMV
#undef FLENS_BLASLOG_BEGIN_GBMV
#endif

#ifdef FLENS_BLASLOG_BEGIN_SBMV
#undef FLENS_BLASLOG_BEGIN_SBMV
#endif
#ifdef FLENS_BLASLOG_BEGIN_SPMV
#undef FLENS_BLASLOG_BEGIN_SPMV
#endif
#ifdef FLENS_BLASLOG_BEGIN_SYMV
#undef FLENS_BLASLOG_BEGIN_SYMV
#endif

#ifdef FLENS_BLASLOG_BEGIN_TBMV
#undef FLENS_BLASLOG_BEGIN_TBMV
#endif
#ifdef FLENS_BLASLOG_BEGIN_TRMV
#undef FLENS_BLASLOG_BEGIN_TRMV
#endif
#ifdef FLENS_BLASLOG_BEGIN_TPMV
#undef FLENS_BLASLOG_BEGIN_TPMV
#endif

#ifdef FLENS_BLASLOG_BEGIN_GBMM
#undef FLENS_BLASLOG_BEGIN_GBMM
#endif
#ifdef FLENS_BLASLOG_BEGIN_GEMM
#undef FLENS_BLASLOG_BEGIN_GEMM
#endif

#ifdef FLENS_BLASLOG_BEGIN_HBMM
#undef FLENS_BLASLOG_BEGIN_HBMM
#endif
#ifdef FLENS_BLASLOG_BEGIN_HEMM
#undef FLENS_BLASLOG_BEGIN_HEMM
#endif

#ifdef FLENS_BLASLOG_BEGIN_TBMM
#undef FLENS_BLASLOG_BEGIN_TBMM
#endif
#ifdef FLENS_BLASLOG_BEGIN_TRMM
#undef FLENS_BLASLOG_BEGIN_TRMM
#endif

#ifdef FLENS_BLASLOG_BEGIN_SBMM
#undef FLENS_BLASLOG_BEGIN_SBMM
#endif
#ifdef FLENS_BLASLOG_BEGIN_SYMM
#undef FLENS_BLASLOG_BEGIN_SYMM
#endif

